### ISSUE TITLE
是否可以添加个”乱序选项“下按照正常顺序显示选项的功能。

### ISSUE THREAD

**Issue by xylinkun** [git9527/anki-awesome-select#10]
先乱序显示选项，让用户答题，显示答案时显示b同正常的顺序。方便用户查看解析。否则解析中的选项序号与显示的答案中的选项序号不一致，几乎没有办法再看原答案的解析。

**Comment by git9527** [comment]
该功能已在个人付费版中提供：https://anki.zhangsn.me/
<img width="523" alt="image" src="https://user-images.githubusercontent.com/4514520/174263090-4096468f-a29d-448f-8538-4df521880a20.png">
