### ISSUE TITLE
请问一下怎么修改默认卡片设置

### ISSUE THREAD

**Issue by ColeLiu** [git9527/anki-awesome-select#2]
我在卡片模板里修改了正面的代码
  var showQuestionType = '1'
  var hideOptions = '0'
  var randomOptions = '1'
  var delayOptions = '0'
  var normalOption = '0'
  var hideNotes = '0'
  var autoFlip = '0'
但是每次打开学习的时候，还是默认的自动翻转打开，其他的关闭。请问一下这个可以修改么，怎么修改呢，谢谢！

**Comment by git9527** [comment]
重构了部分代码，引入了开始的常量

  var DEFAULT_SHOW_QUESTION_TYPE = '0'
  var DEFAULT_HIDE_OPTIONS = '0'
  var DEFAULT_RANDOM_OPTIONS = '0'
  var DEFAULT_DELAY_OPTIONS = '0'
  var DEFAULT_NORMAL_OPTIONS = '0'
  var DEFAULT_HIDE_NOTES = '0'
  var DEFAULT_AUTO_FLIP = '1'

直接改这里的值就行

**Comment by ColeLiu** [comment]
能修改了，谢谢！
