### ISSUE TITLE
IOS 系统无法自动翻转

### ISSUE THREAD

**Issue by yonggithub** [git9527/anki-awesome-select#8]
>7. 自动翻转：默认开启，当选择数量与答案数量一致时，翻转至卡片背面  

经测试, window 上可以实现选中答案卡牌自动翻转. 但在ios系统上, 选中答案后要点一下底部才能显示结果.   
如下图,即使选中所有答案依然没有显示结果. 谢谢.

![4a6b6f74577b853bf1a90650a593437](https://user-images.githubusercontent.com/25076827/160059124-034be8bc-18e8-4978-b884-9715f9e8340c.jpg)

**Comment by git9527** [comment]
重要提示：iOS版本的AnkiMobile在2.0.81版本后更改了内部实现，导致所有设置项及翻转功能无法使用，对于 新版AnkiMobile的支持，在【终极模板】中提供：[Anki终极模板+制卡助手插件](https://zhangsn.me/anki-ultimate-template/)
