### ISSUE TITLE
options选项中不能包含'或"

### ISSUE THREAD

**Issue by yueyinsha** [git9527/anki-awesome-select#9]
我发现当options选项中包含'或"时，正面卡片就只显示question，不显示options了，请问该如何处理呢？

**Comment by git9527** [comment]
var optionArray = '{{options}}'.trim().split("||")

临时解决：当选项中含有单引号时，将上面的单引号换成双引号；当选项中含有双引号时，保持使用单引号
彻底解决：使用商业版的闭源版本：https://zhangsn.me/anki-ultimate-template/
